import ExcelJS from "exceljs";
import type { ReportExportKind, ReportPeriod, ReportQuery } from "@pulseos/types";
import type { Db } from "../../db/client.js";
import { buildOperationsReport, loadReportFacts, UNKNOWN_PATIENT, type ReportFacts } from "./operations-report.service.js";

// Real .xlsx workbooks (Office Open XML via exceljs) built from the SAME fact rows the on-screen report uses, so an
// export always matches what the user was looking at: same tenant, same period, same filters. Dates and times are
// written as text in the hospital's timezone ("02 Oct 2026, 11:00") so nobody's spreadsheet shifts them.

/** Hard ceiling per sheet — a period is at most 366 days, this only stops a pathological tenant from exhausting memory. */
export const EXPORT_ROW_LIMIT = 50_000;

export class ExportTooLargeError extends Error {}

type Col = { header: string; key: string; width: number };

const STATUS_LABEL: Record<string, string> = {
  requested: "Requested", scheduled: "Booked", confirmed: "Confirmed", checked_in: "Checked in", waiting: "Waiting", with_doctor: "With doctor",
  completed: "Completed", no_show: "No-show", cancelled: "Cancelled", pending: "Open", in_progress: "In progress",
};
const STAGE_LABEL: Record<string, string> = {
  enquiry: "Enquiry", contacted: "Contacted", booked: "Appointment booked", attended: "Attended", consulted: "Consulted",
  treatment_advised: "Treatment advised", scheduled: "Procedure scheduled", completed: "Completed", lost: "Lost",
};
const TASK_TYPE_LABEL: Record<string, string> = {
  CALLBACK: "Callback", FOLLOW_UP: "Follow-up", APPOINTMENT_CONFIRMATION: "Appointment confirmation", NO_SHOW_RECOVERY: "No-show recovery",
  TREATMENT_DECISION: "Treatment decision", POST_CARE: "Post-care", RECALL: "Recall", OTHER: "Other",
};
const RANGE_LABEL: Record<string, string> = { today: "Today", yesterday: "Yesterday", "7d": "Last 7 days", "30d": "Last 30 days", this_month: "This month", last_month: "Previous month", custom: "Custom range" };

function dateTime(d: Date | null, timezone: string): string {
  if (!d) return "";
  return new Intl.DateTimeFormat("en-IN", { timeZone: timezone, day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(d);
}

function dayLabel(ymd: string): string {
  return new Intl.DateTimeFormat("en-IN", { timeZone: "UTC", day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${ymd}T00:00:00Z`));
}

const pct = (r: number | null) => (r === null ? "" : Math.round(r * 1000) / 10);
const yesNo = (b: boolean) => (b ? "Yes" : "No");

function addSheet(wb: ExcelJS.Workbook, name: string, cols: Col[], rows: object[]) {
  if (rows.length > EXPORT_ROW_LIMIT) throw new ExportTooLargeError(`${name}: ${rows.length} rows is more than ${EXPORT_ROW_LIMIT}; narrow the period or filters`);
  const ws = wb.addWorksheet(name, { views: [{ state: "frozen", ySplit: 1 }] });
  ws.columns = cols;
  ws.getRow(1).font = { bold: true };
  ws.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8F0FB" } };
  ws.addRows(rows);
  if (rows.length) ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: cols.length } };
  return ws;
}

function filtersSheet(wb: ExcelJS.Workbook, period: ReportPeriod, filterLabels: [string, string][], hospital: string, generatedBy: string, now: Date) {
  const ws = wb.addWorksheet("About");
  ws.columns = [{ header: "", key: "k", width: 26 }, { header: "", key: "v", width: 60 }];
  const rows: [string, string][] = [
    ["Hospital", hospital],
    ["Period", `${RANGE_LABEL[period.range] ?? period.range}: ${dayLabel(period.from)} – ${dayLabel(period.to)}`],
    ["Timezone", period.timezone],
    ...filterLabels,
    ["Generated", dateTime(now, period.timezone)],
    ["Generated by", generatedBy],
  ];
  ws.spliceRows(1, 1);
  for (const [k, v] of rows) ws.addRow({ k, v }).getCell(1).font = { bold: true };
}

function summarySheets(wb: ExcelJS.Workbook, facts: ReportFacts) {
  const r = buildOperationsReport(facts);
  const k = r.kpis;
  addSheet(wb, "Summary", [{ header: "Measure", key: "m", width: 40 }, { header: "Value", key: "v", width: 14 }, { header: "What it counts", key: "d", width: 80 }], [
    { m: "New enquiries", v: k.newEnquiries, d: "Journeys created in the period" },
    { m: "Not yet contacted", v: k.uncontacted, d: "Enquiries of the period still at the Enquiry stage" },
    { m: "No response", v: k.noResponse, d: "Enquiries whose latest outcome is No answer and that got no further" },
    { m: "Follow-ups due", v: k.followUpsDue, d: "Open follow-ups due in the period" },
    { m: "Follow-ups overdue now", v: k.followUpsOverdue, d: "Open follow-ups already past due at the time of export" },
    { m: "Follow-ups completed", v: k.followUpsCompleted, d: "Follow-ups completed in the period" },
    { m: "Appointments booked", v: k.appointmentsBooked, d: "Appointments created in the period" },
    { m: "Appointments scheduled", v: k.appointmentsScheduled, d: "Visits scheduled in the period" },
    { m: "Appointments attended", v: k.appointmentsAttended, d: "Visits in the period the patient attended" },
    { m: "Consultations completed", v: k.consultationsCompleted, d: "Visits in the period whose consultation was completed" },
    { m: "No-shows", v: k.appointmentsNoShow, d: "Visits in the period marked no-show" },
    { m: "Cancelled", v: k.appointmentsCancelled, d: "Visits in the period that were cancelled" },
    { m: "Procedures planned", v: k.proceduresScheduled, d: "Procedures with a planned date in the period (scheduled or done)" },
    { m: "Procedures completed", v: k.proceduresCompleted, d: "Procedures completed in the period, by the recorded completion time (never by payment date)" },
    { m: "Completed, date not recorded", v: k.proceduresCompletedUndated, d: "Completed procedures (all time, same filters) with no completion time recorded — not counted by date" },
    { m: "Converted", v: k.converted, d: "Enquiries of the period whose treatment is completed" },
    { m: "Conversion rate (%)", v: pct(k.conversionRate), d: "Converted ÷ new enquiries" },
  ]);
  addSheet(
    wb,
    "Day by day",
    [
      { header: "Date", key: "day", width: 14 }, { header: "Enquiries", key: "enquiries", width: 11 }, { header: "Appointments scheduled", key: "appointmentsScheduled", width: 22 },
      { header: "Checked in", key: "attended", width: 11 }, { header: "Consultations completed", key: "consultationsCompleted", width: 23 }, { header: "No-show", key: "noShow", width: 10 }, { header: "Cancelled", key: "cancelled", width: 10 },
      { header: "Follow-ups due", key: "followUpsDue", width: 15 }, { header: "Follow-ups completed", key: "followUpsCompleted", width: 20 },
    ],
    r.daily.map((d) => ({ ...d, day: dayLabel(d.day) })),
  );
  addSheet(wb, "Funnel", [{ header: "Stage", key: "label", width: 24 }, { header: "Enquiries reaching it", key: "count", width: 22 }], r.funnel);
  addSheet(
    wb,
    "By source",
    [
      { header: "Source", key: "label", width: 28 }, { header: "Enquiries", key: "enquiries", width: 11 }, { header: "Contacted", key: "contacted", width: 11 },
      { header: "Appointment booked", key: "booked", width: 19 }, { header: "Attended", key: "attended", width: 10 }, { header: "Converted", key: "converted", width: 11 },
      { header: "Conversion (%)", key: "rate", width: 15 },
    ],
    r.bySource.map((s) => ({ ...s, rate: pct(s.conversionRate) })),
  );
  addSheet(
    wb,
    "By service",
    [{ header: "Service", key: "service", width: 28 }, { header: "Enquiries", key: "enquiries", width: 11 }, { header: "Appointment booked", key: "booked", width: 19 }, { header: "Attended", key: "attended", width: 10 }, { header: "Converted", key: "converted", width: 11 }],
    r.byService,
  );
  addSheet(
    wb,
    "By team member",
    [
      { header: "Team member", key: "name", width: 26 }, { header: "Enquiries owned", key: "enquiries", width: 16 }, { header: "Not yet contacted", key: "uncontacted", width: 18 },
      { header: "Follow-ups due", key: "followUpsDue", width: 15 }, { header: "Overdue now", key: "followUpsOverdue", width: 13 }, { header: "Completed", key: "followUpsCompleted", width: 11 },
    ],
    r.byOwner,
  );
}

function enquiriesSheet(wb: ExcelJS.Workbook, facts: ReportFacts) {
  const tz = facts.period.timezone;
  addSheet(
    wb,
    "Enquiries",
    [
      { header: "Created", key: "created", width: 20 }, { header: "Patient", key: "patient", width: 24 }, { header: "Phone", key: "phone", width: 16 },
      { header: "Service", key: "service", width: 20 }, { header: "Source", key: "source", width: 22 }, { header: "Branch", key: "branch", width: 18 },
      { header: "Owner", key: "owner", width: 20 }, { header: "Stage", key: "stage", width: 20 }, { header: "Latest outcome", key: "outcome", width: 22 },
      { header: "Contacted", key: "contacted", width: 11 }, { header: "Appointment booked", key: "booked", width: 19 }, { header: "Attended", key: "attended", width: 10 },
      { header: "Converted", key: "converted", width: 11 },
    ],
    facts.enquiries.map((e) => ({
      created: dateTime(e.createdAt, tz), patient: e.patientName ?? UNKNOWN_PATIENT, phone: e.phone, service: e.service, source: e.sourceLabel ?? e.bucket,
      branch: e.branchName ?? "", owner: e.ownerUserId ? (e.ownerName ?? "Former staff") : "Unassigned", stage: STAGE_LABEL[e.stage] ?? e.stage,
      outcome: e.lastOutcomeLabel ?? "", contacted: yesNo(e.contacted), booked: yesNo(e.booked), attended: yesNo(e.attended), converted: yesNo(e.converted),
    })),
  );
}

function appointmentsSheet(wb: ExcelJS.Workbook, facts: ReportFacts) {
  const tz = facts.period.timezone;
  addSheet(
    wb,
    "Appointments",
    [
      { header: "Scheduled for", key: "at", width: 20 }, { header: "Patient", key: "patient", width: 24 }, { header: "Phone", key: "phone", width: 16 },
      { header: "Doctor", key: "doctor", width: 22 }, { header: "Branch", key: "branch", width: 18 }, { header: "Service", key: "service", width: 20 },
      { header: "Source", key: "source", width: 22 }, { header: "Status", key: "status", width: 14 }, { header: "Booked on", key: "booked", width: 14 },
      { header: "Reason (cancel / no-show / reschedule)", key: "reason", width: 34 },
    ],
    facts.appointments
      .filter((a) => a.scheduledInPeriod)
      .map((a) => ({
        at: dateTime(a.scheduledAt, tz), patient: a.patientName ?? UNKNOWN_PATIENT, phone: a.phone, doctor: a.doctorName ?? "", branch: a.branchName ?? "",
        service: a.service, source: a.sourceLabel ?? a.bucket, status: STATUS_LABEL[a.status] ?? a.status, booked: dayLabel(a.createdDay), reason: (a.reasonCode ?? "").replaceAll("_", " "),
      })),
  );
}

function followUpsSheet(wb: ExcelJS.Workbook, facts: ReportFacts) {
  const tz = facts.period.timezone;
  addSheet(
    wb,
    "Follow-ups",
    [
      { header: "Due", key: "due", width: 20 }, { header: "Type", key: "type", width: 22 }, { header: "Priority", key: "priority", width: 10 },
      { header: "Status", key: "status", width: 12 }, { header: "Overdue now", key: "overdue", width: 12 }, { header: "Patient", key: "patient", width: 24 },
      { header: "Phone", key: "phone", width: 16 }, { header: "Service", key: "service", width: 20 }, { header: "Assigned to", key: "assignee", width: 20 },
      { header: "Completed", key: "completed", width: 20 }, { header: "Note", key: "notes", width: 40 },
    ],
    facts.followUps
      .filter((t) => t.dueInPeriod || t.completedInPeriod)
      .map((t) => ({
        due: dateTime(t.dueAt, tz), type: t.typeLabel ?? TASK_TYPE_LABEL[t.type] ?? t.type, priority: t.priority === "high" ? "High" : "Normal",
        status: STATUS_LABEL[t.status] ?? t.status, overdue: yesNo(t.overdue), patient: t.patientName ?? UNKNOWN_PATIENT, phone: t.phone, service: t.service ?? "",
        assignee: t.assignedTo ? (t.assigneeName ?? "Former staff") : "Unassigned", completed: dateTime(t.completedAt, tz), notes: t.notes ?? "",
      })),
  );
}

const NOT_RECORDED = "Date not recorded";

function proceduresSheet(wb: ExcelJS.Workbook, facts: ReportFacts) {
  const tz = facts.period.timezone;
  // Scheduled for / Completed on / Payment date are three different facts; a missing one is said plainly, never filled in from another.
  addSheet(
    wb,
    "Procedures",
    [
      { header: "Procedure", key: "label", width: 30 }, { header: "Patient", key: "patient", width: 24 }, { header: "Phone", key: "phone", width: 16 },
      { header: "Service", key: "service", width: 20 }, { header: "Status", key: "status", width: 14 }, { header: "Scheduled for", key: "planned", width: 20 },
      { header: "Completed on", key: "completed", width: 20 }, { header: "Payment date", key: "paid", width: 20 }, { header: "Doctor", key: "doctor", width: 22 },
      { header: "Branch", key: "branch", width: 18 }, { header: "Estimated value (₹)", key: "value", width: 18 },
      { header: "In this report", key: "counted", width: 40 },
    ],
    facts.procedures.map((p) => ({
      label: p.label, patient: p.patientName ?? UNKNOWN_PATIENT, phone: p.phone, service: p.service, status: p.status === "COMPLETED" ? "Completed" : "Scheduled",
      planned: p.plannedDate ? dateTime(p.plannedDate, tz) : NOT_RECORDED,
      completed: p.status !== "COMPLETED" ? "" : p.completedAt ? dateTime(p.completedAt, tz) : NOT_RECORDED,
      paid: p.paymentAt ? dateTime(new Date(p.paymentAt), tz) : "",
      doctor: p.doctorName ?? "Doctor not recorded", branch: p.branchName ?? "", value: p.estimatedValue,
      // Reconciles every row with the screen's counts: which KPI (if any) this row is part of for the chosen period.
      counted: [p.plannedInPeriod && "Planned in period", p.completedInPeriod && "Completed in period"].filter(Boolean).join(" · ") || "Not counted — completion date not recorded",
    })),
  );
}

export interface ExportContext {
  hospital: string;
  generatedBy: string;
  filterLabels: [string, string][];
}

export async function buildReportWorkbook(db: Db, tenantId: string, kind: ReportExportKind, q: ReportQuery, ctx: ExportContext, now: Date = new Date()): Promise<{ buffer: Buffer; filename: string; rows: number }> {
  const facts = await loadReportFacts(db, tenantId, q, now);
  const wb = new ExcelJS.Workbook();
  wb.creator = "PulseOS";
  wb.created = now;
  if (kind === "summary") summarySheets(wb, facts);
  if (kind === "enquiries") enquiriesSheet(wb, facts);
  if (kind === "appointments") appointmentsSheet(wb, facts);
  if (kind === "follow-ups") followUpsSheet(wb, facts);
  if (kind === "procedures") proceduresSheet(wb, facts);
  filtersSheet(wb, facts.period, ctx.filterLabels, ctx.hospital, ctx.generatedBy, now);
  const rows = wb.worksheets.filter((w) => w.name !== "About").reduce((s, w) => s + Math.max(0, w.rowCount - 1), 0);
  const buffer = Buffer.from(await wb.xlsx.writeBuffer());
  const span = facts.period.from === facts.period.to ? facts.period.from : `${facts.period.from}_to_${facts.period.to}`;
  const slug = ctx.hospital.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "hospital";
  return { buffer, filename: `pulseos-${kind}-${slug}-${span}.xlsx`, rows };
}
